### ISSUE TITLE
对于一个完全不懂编程的小白还有救吗？

### ISSUE THREAD

**Issue by janzen0816** [Chilfish/Weibo-archiver#1]
看不懂作者在说什么呜呜，进度条走完，为什么点导出没有反应啊，作者大大

另外导出完之后要怎么做才能实现真正备份啊，你写的后面那些不知道该怎么操作，我恨我自己😭

**Comment by Chilfish** [comment]
感谢你的使用，抱歉后续的步骤确实需要需要一点编程基础。因为它的原理是在电脑中启动一个本地网站来呈现导出的数据，并用到 Python 来下载微博里的图片。

现在我重新发了一个版本，可以完成后自动导出了，在 [这里](https://github.com/Chilfish/Weibo-archiver/releases/) 再下载一次最新的脚本。你可以先按最近一周来测试一下，可以了再弄全部的。

导出后是一个压缩包，包含了微博数据(data.mjs)和微博图片(imgs.csv)，同时也要下载并解压 preview.7z 来预览。将 data.mjs 复制粘贴并替换到预览文件夹下的 assets 文件夹中，将 imgs.csv 复制到 preview 文件夹中。

接下来需要下载你的微博图片到电脑里，这一步要下载 Python（[链接](https://www.python.org/downloads/)），按网上教程安装配置就好。然后在 preview 的文件夹中打开命令行窗口（下图这样）

![image](https://github.com/Chilfish/Weibo-archiver/assets/60336739/13f619f9-d10e-432e-b956-dedae3a34780)

然后按下图这样输入 `python ./scripts/download.py -u `，后面是你的微博数字 id，这个数字在网址中有。例如 `https://weibo.com/u/1111681197` 的就是 1111681197。（必须是有 /u/ +数字才对）

![image](https://github.com/Chilfish/Weibo-archiver/assets/60336739/99f8db2d-8e8e-4325-b70b-b45086904c8c)

下载图片可能有点久，它将下载到 preview 文件夹中的 assets/img 目录中。当下载好之后就能用 Python 来预览查看了。这一步还是在 CMD 窗口中输入 `python ./scripts/server.py`，当看到下面的提示之后，就可以在浏览器中打开 `http://localhost:8000` 来查看了

![image](https://github.com/Chilfish/Weibo-archiver/assets/60336739/e80c06bd-493c-4534-a733-4ed238e62556)

可能写得不是很清楚请见谅，一开始没考虑到非编程者的使用方法了，感谢你的提问。另外再说一下就是，可以先试着导出几天的数据来试一下，没问题后再全部导出会好些

**Comment by Chilfish** [comment]
当然，如果你是 Mac 用户，可以按这个步骤来打开在 Mac 上的 “CMD” ，后续步骤应该没差多少

![image](https://github.com/Chilfish/Weibo-archiver/assets/60336739/d7bd1dfe-07d2-4a3f-a5a4-347b41e4c063)

**Comment by janzen0816** [comment]
wow，太感谢了！！❤️
