### ISSUE TITLE
图片链接正则匹配过于宽泛，命中了错误图片地址

### ISSUE THREAD

**Issue by HayashiKaori** [Chilfish/Weibo-archiver#19]
### Bug 描述

如图所示，会匹配到一些奇怪的地址，导致轮询下载失败：

![图片](https://github.com/Chilfish/Weibo-archiver/assets/57685624/d7d18ca6-de1a-4a7e-9d6a-8ed9c71914d4)

**Comment by Chilfish** [comment]
目前解析的图片中，只包括用户头像（自己的和转发的）、微博里的图片、下图转发外链卡片（如b站、网易云）的封面图

![image](https://github.com/Chilfish/Weibo-archiver/assets/60336739/3ba09767-72d5-4f89-9778-8ffaa3679b43)

下面是提取图片链接数组的代码，都只是从返回的微博接口中解析的

https://github.com/Chilfish/Weibo-archiver/blob/f7f771ecc0b15ac33fdcd1f915a585b9920e205f/packages/core/src/utils/parse.ts#L130

https://github.com/Chilfish/Weibo-archiver/blob/f7f771ecc0b15ac33fdcd1f915a585b9920e205f/packages/core/src/utils/parse.ts#L45-L54

不过倒也提醒我忘了把文字的行内查看图片也放进导出的图片数组里了😹

**Comment by Chilfish** [comment]
不过正好发现了另一个问题：带图评论的链接获取错了 `https://photo.weibo.com/h5/comment/compic_id/1022:2305979dc5330f4ba35d04d80af98ecbb4a8e2` 会直接返回一个 html，里面带有真正的图片链接（`http://wx3.sinaimg.cn/large/6a3e9e9egy1hna9gohrxnj20n40ron0k.jpg`），所以下载不了它们

这个将会修好解析的规则，不过还是要兼容之前获取过的图片链接表😅将在下一版修好它
