### ISSUE TITLE
关于新版 (v0.1.11) 更改预览方式与脚本

### ISSUE THREAD

**Issue by Chilfish** [Chilfish/Weibo-archiver#5]
由于拿 Python 来服务 SPA 会有很多难解决的 Bug，最终还是决定使用 vite 来预览结果了。

区别在于改用 Node.js 来下载图片和查看微博，如下图。在 [Node.js 官网](https://nodejs.org/en/download) 下载，然后按 [网上教程](https://zhuanlan.zhihu.com/p/442215189) （类似这个，只要能看到版本号就成功了）

<img width="561" alt="1" src="https://github.com/Chilfish/Weibo-archiver/assets/60336739/89093bce-e1d9-4dcf-b963-e1ebf907df2a">

**Comment by Chilfish** [comment]
才发现 0.1.10 版本的 server.py 有很大的问题，如果是从旧版迁移过来的，只需要复制替换掉 assets 目录下的 img 图片夹和 data.mjs 数据文件，不用重新爬取微博😹

**Comment by SaraKale** [comment]
使用了下十分好用！可见范围内都爬取了，太好了！想问下评论好像爬取不全，是爬取限制吗？评论不全也没事，主要看微博文章~不过每次要运行查看总要输入命令是有点麻烦，期待未来出桌面应用！感谢作者的开发，辛苦了！！😊

**Comment by Chilfish** [comment]
@SaraKale 感谢使用呀~因为爬取评论设计的时候，只考虑到了热评的前几条加上博主发的，而且没有楼中楼。因为这样涉及到比较多微博、评论的时候，会因为太过频繁爬取调用而可能受到微博方面的其他限制，所以就有可能不全了

现在的话可以，可以在 preview 文件夹下新建一个文本文件（txt），重命名为 `weibo.cmd`，然后输入 `node preview.mjs` 命令，之后就能通过双击它来快速启动了🥳

**Comment by SaraKale** [comment]
@Chilfish 原来如此！感谢解答！我看楼中楼米有我的回复我就猜到了怕有限制～对噢，我都忘了可以创建cmd文件！艾玛太久没用都忘记了，感谢提醒！！才发现微博上你关注了我！害羞(/▽＼)，对了给你赞助了一下~，慢慢开发不用着急的！加油哇！

**Comment by Chilfish** [comment]
@SaraKale 好的好的，真是太感谢了🥳
