### ISSUE TITLE
修改导入其他项目保存的json文件后多图无法正常显示

### ISSUE THREAD

**Issue by SingleRottenChips** [Chilfish/Weibo-archiver#52]
### Bug 描述

导入带格式或不带格式的json，该有的key具备，多图无法正常显示，其他信息都显示正常。

请问只有用插件生成的图片才能用默认的CDN吗？

### 复现步骤

用隔壁项目保存的json文件，格式是像这样的，有空格和换行：
<img width="440" alt="截屏2024-05-29 04 28 17" src="https://github.com/Chilfish/Weibo-archiver/assets/63144489/f461c593-fd8f-4713-ab06-f85e5df8f5e9">

导入的那个json, 该有的所有 key 都改好了，uid, name, imgs... 删除不同的key，取消换行并删除空格也没用。

导入后，多图无法显示，单图显示正常。

根据Network判断，可能是css把多条图片链接处理为一个链接了？而单图就没这个问题。

但是我看脚本生成的json的文件也是用逗号隔开的呀...

_刚刚又试了生成无格式的json_，没有换行也没有空格，就是和插件生成的格式一模一样的，导入后多图还法显示。

请问应该怎么做呢？

### 脚本版本

v0.4.0 

### 浏览器版本

Chrome 125.0.6422.77（正式版本） (arm64)

### 错误信息

如下图

### 附加截图

<img width="335" alt="截屏2024-05-29 04 05 15" src="https://github.com/Chilfish/Weibo-archiver/assets/63144489/650fbf76-9461-444c-a4c9-d33b11ad804b">
<img width="804" alt="截屏2024-05-29 04 52 52" src="https://github.com/Chilfish/Weibo-archiver/assets/63144489/6a13a9f4-6aa3-4360-aa3f-4e3416b18677">

**Comment by SingleRottenChips** [comment]
搞了半天突然发现问题了，单个图片链接没有引号... 

感谢大神的开发！

**Comment by Chilfish** [comment]
稍微看了一下，应该是因为其他项目把多个图片用 以逗号为分割 的形式来存储的，而这本应该是一个数组array的，我这里用的是json数组来存储和解析的，所以才会导致这样单个图片没问题(因为没有逗号)

```json
{
  "images": [
    "http://xxx",
    "http://xxx"
  ]
}
```

解决方法也很简单，用正则之类的批量添加数组的 [] 符号和每个图片的双引号就行了
