### ISSUE TITLE
当追加导出最近几天的微博后，再导入，提示导入成功，但是却看不到。

### ISSUE THREAD

**Issue by adrianzhang** [Chilfish/Weibo-archiver#54]
### Bug 描述

微博界面上，追加获取最近两天的微博，然后也得到了json和csv，在本地浏览界面导入，导入的时候用合并的方式，然后导入那两个文件，提示导入成功，57条。然而在本地浏览界面，还是刷不到最近两天的，在日期选择那里选择了起始和终止日期为具体的最近两日，结果为空。

### 复现步骤

先对一个微博全部获取。得到xx.json和xx.csv。导入到本地界面。
等两天，对同样的微博，获取日期选择最近两天的具体日期，等待获取完毕，得到xx(1).json和xx(1).csv。
然后在本地浏览界面点击导入，选择xx(1).json。等待提示导入完成。
然后刷新本地界面。

### 脚本版本

?

### 浏览器版本

Edge

**Comment by Chilfish** [comment]
你好，我试了一下没问题诶，我平时也是过一会就按时间范围导出最近的微博然后再导入的。日期的话，我习惯是始末日都多一天出来。

要不你试试打开浏览器的隐私模式（这样相当于是从新的开始），导入最新的数据，然后再和原来的微博对比一下有什么不同的地方

**Comment by adrianzhang** [comment]
> 你好，我试了一下没问题诶，我平时也是过一会就按时间范围导出最近的微博然后再导入的。日期的话，我习惯是始末日都多一天出来。
> 
> 要不你试试打开浏览器的隐私模式（这样相当于是从新的开始），导入最新的数据，然后再和原来的微博对比一下有什么不同的地方

谢谢这么快反馈。
先补充两个信息：
Edge: v125.0.2535.92正式版（64位）
Weibo Archiver 0.4.0 （油猴脚本）

完全导入是没有问题的，我试了另一个微博关注人，现在相当于获取了两个人的微博。
只有追加最近几天的，会出现问题，而且获取是没问题，因为在weibo.chifish.top/post?page=1界面导入的时候提示多出来多少条，都是对的，只是在这个页面无法浏览到最新的微博。刷了很多次同地址都不行。

**Comment by Chilfish** [comment]
emmm……在隐私窗口导入是为了检查导出最近微博的数据有没有问题，而如果问题出在查看不了合并后的数据就很奇怪了。因为我又在Edge中换了另一个博主导出——先导出上星期的数据，然后是这两天的数据，完全没问题诶

可以试着清除网站的数据，然后再重新导入看看（当然要先保存好先前的文件），同时按 F12 打开浏览器开发工具，看看在终端界面有无其他报错的信息

**Comment by adrianzhang** [comment]
好的，我抽空做一下，然后反馈。

**Comment by adrianzhang** [comment]
今天又获取最近几天的微博，发现正常。
然后用记事本查看前两天的导出文件，果然没有所需日期的微博。不知道当时发生了什么，也许是我获取时选择的日期不对，也许是微博问题，等再遇到问题的时候我仔细看看。
两次出故障都是在工作日早晨。所以我下周再看看。有问题更新。谢谢你的软件和帮助！

**Comment by adrianzhang** [comment]
发现问题所在，追加获取的时候，选择日期，昨天和今天，那么只能获取昨天的。生成的json文件中没有找到今天的微博。

**Comment by Chilfish** [comment]
谢谢你的详细报告，大概是因为代码里时间范围设的不对，应该从0点开始到结束的23:59才对。

刚更新了一下，可以在这里：[预览新版本](https://github.com/Chilfish/Weibo-archiver/actions/runs/9633323397/artifacts/1628997165) 试一下新版

**Comment by adrianzhang** [comment]
> 谢谢你的详细报告，大概是因为代码里时间范围设的不对，应该从0点开始到结束的23:59才对。
> 
> 刚更新了一下，可以在这里：[预览新版本](https://github.com/Chilfish/Weibo-archiver/actions/runs/9633323397/artifacts/1628997165) 试一下新版

谢谢！

这次可以了，能够追加获取到8分钟前新鲜出炉的微博。

小毛病是追加获取的时候，总微博数多了一条，但是导出数据和微博上看到的条数一样。例如部分获取微博4/5这样的，4是能看到的微博总数，是对的，5是错的。
