### ISSUE TITLE
下载微博图片，报错：fetch is not defined

### ISSUE THREAD

**Issue by opqrst123** [Chilfish/Weibo-archiver#57]
### Bug 描述

使用脚本下载图片
全部链接都报错 fetch is not defined

### 复现步骤

1 使用脚本导出微博，勾选导出原图
2 导出成功
3 运行 下载微博图片.bat
4 输入图片地址的csv路径
5 运行，报错

### 脚本版本

[V0.3.7]

### 附加截图

![image](https://github.com/user-attachments/assets/e00a1044-b4e2-4e85-82b5-1744c04e9332)

**Comment by Chilfish** [comment]
这里的 fetch 是脚本运行器自带的一个功能，显示这个信息可能是因为要运行的Nodejs版本过低导致的，需要在 [官网](https://nodejs.org/zh-cn/download/prebuilt-installer) 下载最新的（或大于 20.x） 版本后再试试看

**Comment by opqrst123** [comment]
> 这里的 fetch 是脚本运行器自带的一个功能，显示这个信息可能是因为要运行的Nodejs版本过低导致的，需要在 [官网](https://nodejs.org/zh-cn/download/prebuilt-installer) 下载最新的（或大于 20.x） 版本后再试试看

更新版本后可以了 谢谢
