### ISSUE TITLE
想请教问题

### ISSUE THREAD

**Issue by Philae994** [Chilfish/Weibo-archiver#6]
项目很好用，感谢付出。
我在使用中遇到几个问题，比如https://weibo.com/u/1304194202，我获取日期输入2023-05-31至2023-12-15 只能获取2023-07-07至2023-12-15的66条微博，而2023-06-01至2023-07-07之间还有微博没有获取到。
于是我再次获取2023-05-31至2023-07-07之间的微博，并用合并命令合并，将2023-05-31至2023-07-07的imgs.csv中的内容复制到2023-07-07至2023-12-15的imgs.csv里。再次运行下载图片命令后并不能下载2023-05-31至2023-07-07这期间的图片。

**Comment by Chilfish** [comment]
感谢反馈😇我才发现在循环获取日期范围内微博的写法漏了个判断，所以才会导致没获取全，现在修好了，下 v0.1.12 版就好😹

至于第二个问题，可能是因为粘贴的格式不对。图片的链接要像前面的那样，按照 英文逗号然后换行 的格式才能正确解析。或者说你贴个下载失败的截图看看（如果有的话）

**Comment by Philae994** [comment]
> 感谢反馈😇我才发现在循环获取日期范围内微博的写法漏了个判断，所以才会导致没获取全，现在修好了，下 v0.1.12 版就好😹
> 
> 至于第二个问题，可能是因为粘贴的格式不对。图片的链接要像前面的那样，按照 英文逗号然后换行 的格式才能正确解析。或者说你贴个下载失败的截图看看（如果有的话）

图片下载问题是使用node ./download.mjs -u  命令后直接显示下载完成，现在用python3 ./download.py -u命令重新下载了一遍，全部下完了，打开网页后只有某些条中的个别图片显示加载失败。
谢谢表哥！

**Comment by Chilfish** [comment]
Okk，没啥别的问题就关了🥳
